# Generated by Django 4.2.23 on 2025-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_Shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
