# Generated by Django 4.2.23 on 2025-08-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_Shop', '0002_registrationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
